// Static destination data for Andhra Pradesh - Complete 44 destinations
export const staticDestinations = [
  // PILGRIMAGE SITES (15 destinations)
  {
    id: 1,
    name: "Tirumala Venkateswara Temple",
    location: "Tirupati, Chittoor District",
    category: "Pilgrimage",
    description: "Sacred temple of Lord Venkateswara, one of the most visited religious sites in the world",
    image: "https://assets.thehansindia.com/h-upload/2023/08/25/1375351-ttd.webp",
    rating: 4.8,
    entryFee: "Free",
    bestTime: "October to March",
    highlights: ["Ancient temple architecture", "Spiritual experience", "Laddu prasadam"]
  },
  {
    id: 2,
    name: "Srisailam Temple",
    location: "Kurnool District",
    category: "Pilgrimage",
    description: "One of the 12 Jyotirlingas dedicated to Lord Shiva, situated on Krishna River banks",
    image: "https://tse1.mm.bing.net/th/id/OIP.6fzouDEZlPEjCpr9ye2hdAHaDt?pid=Api&P=0&h=180",
    rating: 4.7,
    entryFee: "Free",
    bestTime: "October to March",
    highlights: ["Jyotirlinga temple", "River cruise", "Wildlife sanctuary"]
  },
  {
    id: 3,
    name: "Simhachalam Temple",
    location: "Visakhapatnam District",
    category: "Pilgrimage",
    description: "Ancient temple dedicated to Lord Narasimha on hilltop with scenic views",
    image: "https://tfiglobalnews.com/wp-content/uploads/2022/12/Simhachalam-Temple-compex.jpg",
    rating: 4.5,
    entryFee: "Free",
    bestTime: "October to March",
    highlights: ["Hilltop temple", "Temple museum", "Panoramic views"]
  },
  {
    id: 4,
    name: "Sri Kalahasti Temple",
    location: "Chittoor District",
    category: "Pilgrimage",
    description: "Vayu Sthalam representing air element, famous for Rahu-Ketu prayers",
    image: "https://tse1.mm.bing.net/th/id/OIP.n0HsvFm6fUAkVW8YJTXU2gHaCu?pid=Api&P=0&h=180",
    rating: 4.6,
    entryFee: "Free",
    bestTime: "October to March",
    highlights: ["Pancha Bhoota Sthalam", "Rahu-Ketu remedies", "Ancient architecture"]
  },
  {
    id: 5,
    name: "Kanipakam Temple",
    location: "Chittoor District",
    category: "Pilgrimage",
    description: "Famous Ganesha temple where the idol is believed to be growing in size",
    image: "https://tse2.mm.bing.net/th/id/OIP.ze1XcJgK5llT8F0kS-KiOgHaE6?pid=Api&P=0&h=180",
    rating: 4.5,
    entryFee: "Free",
    bestTime: "October to March",
    highlights: ["Growing Ganesha idol", "Sacred tank", "Healing powers"]
  },
  {
    id: 6,
    name: "Annavaram Temple",
    location: "East Godavari District",
    category: "Pilgrimage",
    description: "Hilltop temple dedicated to Lord Satyanarayana Swamy with scenic ghat road",
    image: "https://tse1.mm.bing.net/th/id/OIP.GUcklajXFiNWllx6UM2IXQHaEc?pid=Api&P=0&h=180",
    rating: 4.6,
    entryFee: "Free",
    bestTime: "October to March",
    highlights: ["Lord Satyanarayana shrine", "Scenic ghat road", "Temple museum"]
  },
  {
    id: 7,
    name: "Kanaka Durga Temple",
    location: "Vijayawada, Krishna District",
    category: "Pilgrimage",
    description: "Goddess Durga temple on Indrakeeladri hill overlooking Krishna River",
    image: "https://tse3.mm.bing.net/th/id/OIP.o9pvHROGtz90nOUDmPDhZwHaDt?pid=Api&P=0&h=180",
    rating: 4.5,
    entryFee: "Free",
    bestTime: "October to March",
    highlights: ["River views", "Cable car", "Navratri celebrations"]
  },
  {
    id: 8,
    name: "Yaganti Temple",
    location: "Kurnool District",
    category: "Pilgrimage",
    description: "Uma Maheshwara temple famous for growing Nandi statue",
    image: "https://tfipost.com/wp-content/uploads/2022/12/Yaganti_Uma_Maheswara_Temple.jpg",
    rating: 4.4,
    entryFee: "Free",
    bestTime: "October to March",
    highlights: ["Growing Nandi", "Cave temple", "Natural formations"]
  },
  {
    id: 9,
    name: "Bhadrachalam Temple",
    location: "East Godavari District",
    category: "Pilgrimage",
    description: "Lord Rama temple on the banks of river Godavari",
    image: "https://tripxl.com/blog/wp-content/uploads/2024/08/Bhadrachalam-Temple-OG-Image.jpg",
    rating: 4.4,
    entryFee: "Free",
    bestTime: "October to March",
    highlights: ["Rama temple", "Godavari river", "Cultural significance"]
  },
  {
    id: 10,
    name: "Ahobilam Temple",
    location: "Kurnool District",
    category: "Pilgrimage",
    description: "Nine temples dedicated to Lord Narasimha in Nallamala Hills",
    image: "https://tse2.mm.bing.net/th/id/OIP.NH95FsE5C7GY9UICZVzMOAHaFj?pid=Api&P=0&h=180",
    rating: 4.3,
    entryFee: "Free",
    bestTime: "October to March",
    highlights: ["Nine Narasimha temples", "Forest trekking", "Scenic location"]
  },
  {
    id: 11,
    name: "Srikalahasti",
    location: "Chittoor District",
    category: "Pilgrimage",
    description: "Ancient Shiva temple representing the wind element",
    image: "https://www.holidify.com/images/cmsuploads/compressed/225(1)_20180206113353.jpg",
    rating: 4.5,
    entryFee: "Free",
    bestTime: "October to March",
    highlights: ["Vayu linga", "Ancient architecture", "Spiritual significance"]
  },
  {
    id: 12,
    name: "Mantralayam",
    location: "Kurnool District",
    category: "Pilgrimage",
    description: "Holy place dedicated to Sri Raghavendra Swamy",
    image: "https://tse3.mm.bing.net/th/id/OIP.C6_xI2yifusvsDTupaMQBwHaD4?pid=Api&P=0&h=180",
    rating: 4.4,
    entryFee: "Free",
    bestTime: "October to March",
    highlights: ["Raghavendra Swamy shrine", "Sacred wells", "Miracle stories"]
  },
  {
    id: 13,
    name: "Puttaparthi",
    location: "Anantapur District",
    category: "Pilgrimage",
    description: "Birthplace of Sri Sathya Sai Baba with ashram and spiritual center",
    image: "https://tse3.mm.bing.net/th/id/OIP.pGWVE-rEMsUbG0ydZblQDwHaDS?pid=Api&P=0&h=180",
    rating: 4.3,
    entryFee: "Free",
    bestTime: "October to March",
    highlights: ["Sai Baba ashram", "Spiritual programs", "International visitors"]
  },
  {
    id: 14,
    name: "Dwaraka Tirumala",
    location: "West Godavari District",
    category: "Pilgrimage",
    description: "Chinna Tirupati with Lord Venkateswara temple",
    image: "https://tse2.mm.bing.net/th/id/OIP.O4lkHHrR8rFcv87vtalrMgHaE8?pid=Api&P=0&h=180",
    rating: 4.2,
    entryFee: "Free",
    bestTime: "October to March",
    highlights: ["Venkateswara temple", "Peaceful atmosphere", "River location"]
  },
  {
    id: 15,
    name: "Penusila",
    location: "Krishna District",
    category: "Pilgrimage",
    description: "Lakshmi Narasimha Swamy temple with ancient significance",
    image: "https://tse3.mm.bing.net/th/id/OIP.KzAktygDYFPXhLlPp2VuqwHaEK?pid=Api&P=0&h=180",
    rating: 4.1,
    entryFee: "Free",
    bestTime: "October to March",
    highlights: ["Narasimha temple", "Historical importance", "Peaceful setting"]
  },

  // HILL STATIONS (5 destinations)
  {
    id: 16,
    name: "Araku Valley",
    location: "Visakhapatnam District",
    category: "Hill Station",
    description: "Beautiful hill station known for coffee plantations and tribal culture",
    image: "https://vizagtourism.org.in/images/places-to-visit/header/araku-valley-vizag-tourism-entry-fee-timings-holidays-reviews-header.jpg",
    rating: 4.6,
    entryFee: "₹20",
    bestTime: "October to February",
    highlights: ["Coffee plantations", "Tribal museum", "Scenic train journey"]
  },
  {
    id: 17,
    name: "Horsley Hills",
    location: "Chittoor District",
    category: "Hill Station",
    description: "Summer retreat with pleasant climate and environmental park",
    image: "https://lifeandtrendz.com/wp-content/uploads/2021/02/horsley1.jpg",
    rating: 4.3,
    entryFee: "₹20",
    bestTime: "March to June, October to February",
    highlights: ["Pleasant climate", "Environmental park", "Boating"]
  },
  {
    id: 18,
    name: "Chintapalli",
    location: "Visakhapatnam District",
    category: "Hill Station",
    description: "Hill station famous for coffee and pepper plantations",
    image: "https://tse3.mm.bing.net/th/id/OIP.1ziDa3hs4D_dilPn03v2tgHaEQ?pid=Api&P=0&h=180",
    rating: 4.2,
    entryFee: "₹15",
    bestTime: "October to March",
    highlights: ["Coffee estates", "Pepper plantations", "Tribal culture"]
  },
  {
    id: 19,
    name: "Lambasingi",
    location: "Visakhapatnam District",
    category: "Hill Station",
    description: "Kashmir of Andhra Pradesh with zero degree temperatures",
    image: "https://www.noblehousetours.com/wp-content/uploads/2017/10/the-kashmir-of-south-india.jpg",
    rating: 4.4,
    entryFee: "Free",
    bestTime: "November to February",
    highlights: ["Zero degrees", "Misty weather", "Unique climate"]
  },
  {
    id: 20,
    name: "Ananthagiri Hills",
    location: "Visakhapatnam District",
    category: "Hill Station",
    description: "Scenic hills with caves and waterfalls near Araku",
    image: "https://img.traveltriangle.com/blog/wp-content/uploads/2019/11/Ananthgiri-hills-22_nov1.jpg",
    rating: 4.1,
    entryFee: "₹10",
    bestTime: "October to March",
    highlights: ["Natural caves", "Waterfalls", "Trekking trails"]
  },

  // COASTAL DESTINATIONS (8 destinations)
  {
    id: 21,
    name: "Rishikonda Beach",
    location: "Visakhapatnam District",
    category: "Coastal",
    description: "Pristine golden sand beach popular for water sports and beach activities",
    image: "https://i.ytimg.com/vi/I8__eSoHKag/maxresdefault.jpg",
    rating: 4.5,
    entryFee: "Free",
    bestTime: "November to March",
    highlights: ["Water sports", "Golden sand", "Beach resorts"]
  },
  {
    id: 22,
    name: "Kakinada Beach",
    location: "East Godavari District",
    category: "Coastal",
    description: "Coastal city with beautiful beaches and Coringa mangrove sanctuary",
    image: "https://tripxl.com/blog/wp-content/uploads/2024/08/Kakinada-Beach-2.jpg",
    rating: 4.4,
    entryFee: "₹30",
    bestTime: "November to March",
    highlights: ["Mangrove sanctuary", "Lighthouse", "Boat safari"]
  },
  {
    id: 23,
    name: "Uppada Beach",
    location: "East Godavari District",
    category: "Coastal",
    description: "Pristine beach famous for handloom sarees and peaceful atmosphere",
    image: "https://tse1.mm.bing.net/th/id/OIP.xH2l22XDaQS8phU4j_fF8wHaDu?pid=Api&P=0&h=180",
    rating: 4.2,
    entryFee: "Free",
    bestTime: "November to March",
    highlights: ["Handloom sarees", "Peaceful beach", "Fishing village"]
  },
  {
    id: 24,
    name: "Machilipatnam Beach",
    location: "Krishna District",
    category: "Coastal",
    description: "Historic port town with lighthouse and Dutch heritage",
    image: "https://tse3.mm.bing.net/th/id/OIP.cQZbItIqYFASwfD1g5XWbQAAAA?pid=Api&P=0&h=180",
    rating: 4.0,
    entryFee: "Free",
    bestTime: "November to March",
    highlights: ["Historic lighthouse", "Dutch heritage", "Port town"]
  },
  {
    id: 25,
    name: "Mypad Beach",
    location: "Nellore District",
    category: "Coastal",
    description: "Serene beach with golden sand and peaceful environment",
    image: "https://2.bp.blogspot.com/-ZXD2binO49w/WPi0MbjfzRI/AAAAAAABVXU/0_GvlA01NaIgC2ckPOzXvHBA5d7NpaGSwCLcB/s1600/mypadu%2Bbeach%2Bandhra%2Bpradesh%2Bwater%2Bsports%2Btourism%2Bindia.jpg",
    rating: 4.0,
    entryFee: "Free",
    bestTime: "November to March",
    highlights: ["Golden sand", "Peaceful atmosphere", "Sunset views"]
  },
  {
    id: 26,
    name: "Suryalanka Beach",
    location: "Guntur District",
    category: "Coastal",
    description: "Clean beach with recreational facilities and water sports",
    image: "https://tse3.mm.bing.net/th/id/OIP.bo1IXugzgLR3mXg0jks-kgHaEL?pid=Api&P=0&h=180",
    rating: 4.1,
    entryFee: "₹20",
    bestTime: "November to March",
    highlights: ["Water sports", "Clean beach", "Recreational facilities"]
  },
  {
    id: 27,
    name: "Vodarevu Beach",
    location: "Prakasam District",
    category: "Coastal",
    description: "Tranquil beach known for turtle nesting and natural beauty",
    image: "https://tse4.mm.bing.net/th/id/OIP.eZYydl7DXOaQXkQzhbrLpQHaEC?pid=Api&P=0&h=180",
    rating: 3.9,
    entryFee: "Free",
    bestTime: "November to March",
    highlights: ["Turtle nesting", "Natural beauty", "Quiet atmosphere"]
  },
  {
    id: 28,
    name: "Mypadu Beach",
    location: "Nellore District",
    category: "Coastal",
    description: "Beautiful beach with black soil and peaceful surroundings",
    image: "https://2.bp.blogspot.com/-ZXD2binO49w/WPi0MbjfzRI/AAAAAAABVXU/0_GvlA01NaIgC2ckPOzXvHBA5d7NpaGSwCLcB/s1600/mypadu%2Bbeach%2Bandhra%2Bpradesh%2Bwater%2Bsports%2Btourism%2Bindia.jpg",
    rating: 3.8,
    entryFee: "Free",
    bestTime: "November to March",
    highlights: ["Black soil beach", "Peaceful", "Local fishing"]
  },

  // NATURAL ATTRACTIONS (10 destinations)
  {
    id: 29,
    name: "Gandikota",
    location: "Kadapa District",
    category: "Natural",
    description: "Known as 'Grand Canyon of India' with spectacular gorge views",
    image: "https://i.redd.it/cy5e3cb6hbl51.jpg",
    rating: 4.7,
    entryFee: "₹20",
    bestTime: "October to March",
    highlights: ["Canyon views", "Ancient fort", "Camping"]
  },
  {
    id: 30,
    name: "Belum Caves",
    location: "Kurnool District",
    category: "Natural",
    description: "India's longest cave system with spectacular stalactite formations",
    image: "https://tse1.mm.bing.net/th/id/OIP.gXGQoM-xIOpUTymDZf4XOQHaDt?pid=Api&P=0&h=180",
    rating: 4.5,
    entryFee: "₹25",
    bestTime: "October to March",
    highlights: ["Cave exploration", "Limestone formations", "Underground chambers"]
  },
  {
    id: 31,
    name: "Borra Caves",
    location: "Visakhapatnam District",
    category: "Natural",
    description: "Million-year-old limestone caves with unique geological formations",
    image: "https://www.trawell.in/admin/images/upload/249844919BorraCaves_Main.jpg",
    rating: 4.4,
    entryFee: "₹40",
    bestTime: "October to March",
    highlights: ["Limestone caves", "Natural formations", "Shivalinga rock"]
  },
  {
    id: 32,
    name: "Talakona Waterfalls",
    location: "Chittoor District",
    category: "Natural",
    description: "Highest waterfall in Andhra Pradesh located in dense forest",
    image: "https://media-cdn.tripadvisor.com/media/photo-s/03/2d/d0/47/talakona-waterfall.jpg",
    rating: 4.3,
    entryFee: "₹30",
    bestTime: "June to January",
    highlights: ["270 feet waterfall", "Forest trekking", "Medicinal plants"]
  },
  {
    id: 33,
    name: "Papikondalu",
    location: "East Godavari District",
    category: "Natural",
    description: "Scenic hills along Godavari River with boat cruises",
    image: "https://www.telanganaboattourism.com/assets/images/papikondalu-900x500.jpg",
    rating: 4.7,
    entryFee: "₹500 (cruise)",
    bestTime: "October to March",
    highlights: ["River cruise", "Scenic hills", "Tribal villages"]
  },
  {
    id: 34,
    name: "Kolleru Lake",
    location: "West Godavari District",
    category: "Natural",
    description: "Largest freshwater lake and important bird sanctuary",
    image: "https://static2.tripoto.com/media/filter/nl/img/267449/TripDocument/1503312681_lake_2.jpeg",
    rating: 4.3,
    entryFee: "₹20",
    bestTime: "November to February",
    highlights: ["Bird watching", "Migratory birds", "Boat rides"]
  },
  {
    id: 35,
    name: "Pulicat Lake",
    location: "Nellore District",
    category: "Natural",
    description: "Brackish water lagoon famous for flamingo sightings",
    image: "https://imgstaticcontent.lbb.in/lbbnew/wp-content/uploads/2017/11/02074935/PulicatLake.jpg",
    rating: 4.2,
    entryFee: "₹25",
    bestTime: "November to February",
    highlights: ["Flamingo watching", "Boat safari", "Bird sanctuary"]
  },
  {
    id: 36,
    name: "Ethipothala Waterfalls",
    location: "Guntur District",
    category: "Natural",
    description: "Beautiful waterfall with crocodile breeding center nearby",
    image: "https://tse4.mm.bing.net/th/id/OIP.0VJEqg_6ALrC_yHnBqWz-wHaFj?pid=Api&P=0&h=180",
    rating: 4.3,
    entryFee: "₹20",
    bestTime: "June to February",
    highlights: ["Scenic waterfall", "Crocodile center", "Boating"]
  },
  {
    id: 37,
    name: "Kailasagiri",
    location: "Visakhapatnam District",
    category: "Natural",
    description: "Hilltop park with panoramic city views and cable car",
    image: "https://vizagtourism.org.in/images/places-to-visit/header/kailasagiri-park-vizag-tourism-entry-fee-timings-holidays-reviews-header.jpg",
    rating: 4.4,
    entryFee: "₹30",
    bestTime: "October to March",
    highlights: ["City views", "Cable car", "Shiva-Parvati statue"]
  },
  {
    id: 38,
    name: "Nagarjuna Sagar",
    location: "Nalgonda District",
    category: "Natural",
    description: "Massive dam with Buddhist heritage sites and boat rides",
    image: "https://i.pinimg.com/originals/86/d7/65/86d765162d9fe64cc20c5cf616016cf2.jpg",
    rating: 4.3,
    entryFee: "₹50",
    bestTime: "October to March",
    highlights: ["Massive dam", "Buddhist sites", "Boat rides"]
  },

  // HISTORICAL SITES (6 destinations)
  {
    id: 39,
    name: "Amaravati",
    location: "Guntur District",
    category: "Historical",
    description: "Historic capital city with ancient Buddhist stupas and modern architecture",
    image: "https://media.istockphoto.com/id/1285899035/photo/tall-buddha-statue-in-andhra-pradesh-state-amaravathi-india.jpg?s=170667a&w=0&k=20&c=WtYYoNUuLXYU34O-5XSgQpPC3YbuJv-fE915vTHaZRE=",
    rating: 4.3,
    entryFee: "₹15",
    bestTime: "November to February",
    highlights: ["Buddhist heritage", "Amaravathi stupa", "Archaeological museum"]
  },
  {
    id: 40,
    name: "Lepakshi",
    location: "Anantapur District",
    category: "Historical",
    description: "Historic village famous for hanging pillar and Veerabhadra temple",
    image: "https://tse1.mm.bing.net/th/id/OIP.U4J8EaIv6CK4E5AQmUfKhQHaE6?pid=Api&P=0&h=180",
    rating: 4.4,
    entryFee: "₹15",
    bestTime: "October to March",
    highlights: ["Hanging pillar", "Nandi statue", "Fresco paintings"]
  },
  {
    id: 41,
    name: "Chandragiri Fort",
    location: "Chittoor District",
    category: "Historical",
    description: "Medieval fort with palaces and historical significance",
    image: "https://i.ytimg.com/vi/PG__ngKDS5w/maxresdefault.jpg",
    rating: 4.1,
    entryFee: "₹25",
    bestTime: "October to March",
    highlights: ["Medieval architecture", "Raja Mahal", "Sound and light show"]
  },
  {
    id: 42,
    name: "Kondaveedu Fort",
    location: "Guntur District",
    category: "Historical",
    description: "Ruined hilltop fort with panoramic views and rich history",
    image: "https://mews.in/wp-content/uploads/2021/12/Kondaveedu-Fort.jpg",
    rating: 4.0,
    entryFee: "₹20",
    bestTime: "October to March",
    highlights: ["Hilltop fort", "Panoramic views", "Ancient ruins"]
  },
  {
    id: 43,
    name: "Golconda Fort Extension",
    location: "telangana",
    category: "Historical",
    description: "Historical fort ruins with architectural significance",
    image: "http://image3.mouthshut.com/images/Restaurant/Photo/-99128_8915.jpg",
    rating: 3.9,
    entryFee: "₹15",
    bestTime: "October to March",
    highlights: ["Ancient architecture", "Historical ruins", "Strategic location"]
  },
  {
    id: 44,
    name: "Undavalli Caves",
    location: "Guntur District",
    category: "Historical",
    description: "Rock-cut caves with ancient Buddhist and Hindu architecture",
    image: "https://imgcld.yatra.com/ytimages/image/upload/t_monuments_detailslargeimg/v1528097243/Monuments/a0475612-ac0d-48e3-8aad-a416f9dce3c6/Undavalli_Caves_juusUl.jpg",
    rating: 4.2,
    entryFee: "₹25",
    bestTime: "October to March",
    highlights: ["Rock-cut architecture", "Ancient sculptures", "Multi-story caves"]
  }
];

// Static hotel data for Andhra Pradesh - Complete accommodation options
export const staticHotels = [
  // LUXURY HOTELS (3 hotels)
  {
    id: 1,
    name: "The Park Visakhapatnam",
    location: "Visakhapatnam",
    category: "Luxury",
    type: "5-Star Beach Resort",
    description: "Beachfront luxury hotel with stunning ocean views and modern amenities",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2080&q=80",
    rating: 4.7,
    pricePerNight: 8500,
    amenities: ["Beach Access", "Ocean View Spa", "Multiple Restaurants", "Pool Bar", "Water Sports", "Kids Club"],
    roomTypes: ["Ocean View Room", "Beach Suite", "Presidential Suite"],
    nearbyAttractions: ["Rishikonda Beach", "Kailasagiri", "Submarine Museum"],
    features: ["Beach Activities", "Sunset Views", "Marine Sports", "Beachside Dining"]
  },
  {
    id: 2,
    name: "Fortune Select Grand Ridge",
    location: "Tirupati",
    category: "Luxury",
    type: "4-Star Hotel",
    description: "Premium hotel catering to pilgrims and business travelers",
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
    rating: 4.5,
    pricePerNight: 6500,
    amenities: ["Temple Shuttle", "Vegetarian Restaurant", "Spa", "Fitness Center", "Business Center", "Banquet Halls"],
    roomTypes: ["Superior Room", "Deluxe Room", "Executive Suite"],
    nearbyAttractions: ["Tirumala Temple", "Sri Venkateswara Museum", "Chandragiri Fort"],
    features: ["Pilgrim Services", "Early Check-in", "Temple Tours", "Religious Activities"]
  },
  {
    id: 3,
    name: "Hotel Bliss",
    location: "Vijayawada",
    category: "Luxury",
    type: "4-Star Hotel", 
    description: "Elegant hotel offering comfort and convenience in the heart of the city",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/City_hotel_exterior.jpg/800px-City_hotel_exterior.jpg",
    rating: 4.4,
    pricePerNight: 5500,
    amenities: ["City Views", "Multi-cuisine Restaurant", "Banquet Facilities", "Business Center", "Gym", "Travel Desk"],
    roomTypes: ["Standard Room", "Deluxe Room", "Executive Suite"],
    nearbyAttractions: ["Kanaka Durga Temple", "Prakasam Barrage", "Undavalli Caves"],
    features: ["Central Location", "River Views", "Cultural Tours", "Business Services"]
  },

  // MID-RANGE HOTELS (6 hotels)
  {
    id: 4,
    name: "Hotel Haritha Valley Resort",
    location: "Araku Valley",
    category: "Mid-Range",
    type: "Hill Resort",
    description: "Scenic resort nestled in the hills with coffee plantation views",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
    rating: 4.2,
    pricePerNight: 3500,
    amenities: ["Valley Views", "Coffee Tours", "Trekking", "Bonfire", "Local Cuisine", "Nature Walks"],
    roomTypes: ["Hill View Room", "Valley Suite", "Cottage"],
    nearbyAttractions: ["Coffee Plantations", "Borra Caves", "Tribal Museum"],
    features: ["Mountain Air", "Coffee Experience", "Tribal Culture", "Nature Activities"]
  },
  {
    id: 5,
    name: "Hotel Mayura",
    location: "Kurnool",
    category: "Mid-Range",
    type: "Business Hotel",
    description: "Comfortable hotel with modern amenities and good connectivity",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/m/m2/Business_hotel_front.jpg/800px-Business_hotel_front.jpg",
    rating: 4.0,
    pricePerNight: 2800,
    amenities: ["Restaurant", "Conference Room", "WiFi", "Travel Assistance", "Laundry", "Room Service"],
    roomTypes: ["Standard Room", "Deluxe Room", "Family Suite"],
    nearbyAttractions: ["Belum Caves", "Srisailam Temple", "Rollapadu Wildlife Sanctuary"],
    features: ["Business Facilities", "Local Tours", "Comfortable Stay", "Value for Money"]
  },
  {
    id: 6,
    name: "Hotel Dwaraka Inn",
    location: "Rajahmundry",
    category: "Mid-Range",
    type: "River View Hotel",
    description: "Riverside hotel offering peaceful stay with Godavari river views",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/r/r7/Riverside_hotel.jpg/800px-Riverside_hotel.jpg",
    rating: 4.1,
    pricePerNight: 3200,
    amenities: ["River Views", "Boat Arrangements", "Regional Cuisine", "Cultural Programs", "Garden", "Parking"],
    roomTypes: ["River View Room", "Deluxe Room", "Executive Suite"],
    nearbyAttractions: ["Godavari River", "Papikondalu", "ISKCON Temple"],
    features: ["River Activities", "Boat Cruises", "Cultural Experience", "Peaceful Setting"]
  },
  {
    id: 7,
    name: "Hotel Sitara Grand",
    location: "Guntur",
    category: "Mid-Range", 
    type: "City Hotel",
    description: "Well-appointed hotel in the commercial heart of Guntur",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Commercial_hotel.jpg/800px-Commercial_hotel.jpg",
    rating: 3.9,
    pricePerNight: 2500,
    amenities: ["Multi-cuisine Restaurant", "Banquet Hall", "Business Center", "WiFi", "Parking", "Travel Desk"],
    roomTypes: ["Standard Room", "Premium Room", "Business Suite"],
    nearbyAttractions: ["Amaravati", "Undavalli Caves", "Kondaveedu Fort"],
    features: ["Central Location", "Business Services", "Local Connectivity", "Affordable Luxury"]
  },
  {
    id: 8,
    name: "Beach Road Hotel",
    location: "Visakhapatnam",
    category: "Mid-Range",
    type: "Beach Hotel",
    description: "Beachfront hotel with easy access to popular beaches and attractions",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Beachfront_hotel.jpg/800px-Beachfront_hotel.jpg",
    rating: 4.3,
    pricePerNight: 4200,
    amenities: ["Beach Access", "Sea View Restaurant", "Water Sports", "Beach Volleyball", "Seafood Specialties", "Beach Equipment"],
    roomTypes: ["Sea View Room", "Beach Suite", "Family Room"],
    nearbyAttractions: ["RK Beach", "Submarine Museum", "Kailasagiri"],
    features: ["Beach Activities", "Water Sports", "Seafood Dining", "Ocean Views"]
  },
  {
    id: 9,
    name: "Hotel Srinivasa",
    location: "Chittoor",
    category: "Mid-Range",
    type: "Pilgrim Hotel",
    description: "Comfortable accommodation for pilgrims visiting nearby temples",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/p/p9/Pilgrim_hotel.jpg/800px-Pilgrim_hotel.jpg",
    rating: 4.0,
    pricePerNight: 2200,
    amenities: ["Temple Tours", "Vegetarian Restaurant", "Early Check-in", "Luggage Storage", "Travel Assistance", "Prayer Room"],
    roomTypes: ["Standard Room", "Family Room", "Group Accommodation"],
    nearbyAttractions: ["Tirupati", "Kalahasti Temple", "Horsley Hills"],
    features: ["Pilgrim Services", "Temple Connectivity", "Spiritual Atmosphere", "Budget-Friendly"]
  },

  // BUDGET HOTELS (6 hotels)
  {
    id: 10,
    name: "Hotel Annapurna",
    location: "Vijayawada",
    category: "Budget",
    type: "Economy Hotel",
    description: "Clean and comfortable budget accommodation with essential amenities",
    image: "https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2071&q=80",
    rating: 3.8,
    pricePerNight: 1500,
    amenities: ["Restaurant", "WiFi", "24-hour Front Desk", "Room Service", "Laundry", "Parking"],
    roomTypes: ["Standard Room", "Deluxe Room", "Family Room"],
    nearbyAttractions: ["Kanaka Durga Temple", "Prakasam Barrage", "Gandhi Hill"],
    features: ["Value for Money", "Clean Rooms", "Good Location", "Basic Amenities"]
  },
  {
    id: 11,
    name: "City Inn",
    location: "Kakinada",
    category: "Budget",
    type: "City Hotel",
    description: "Affordable hotel near port area with basic modern amenities",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/City_inn_building.jpg/800px-City_inn_building.jpg",
    rating: 3.7,
    pricePerNight: 1800,
    amenities: ["Restaurant", "WiFi", "Air Conditioning", "Room Service", "Travel Desk", "Parking"],
    roomTypes: ["Standard Room", "Deluxe Room"],
    nearbyAttractions: ["Kakinada Beach", "Coringa Wildlife Sanctuary", "Uppada Beach"],
    features: ["Port Connectivity", "Business Travel", "Coast Access", "Affordable Rates"]
  },
  {
    id: 12,
    name: "Tourist Lodge",
    location: "Horsley Hills",
    category: "Budget",
    type: "Hill Station Lodge",
    description: "Government-run lodge offering basic accommodation in scenic hills",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/t/t8/Hill_station_lodge.jpg/800px-Hill_station_lodge.jpg",
    rating: 3.5,
    pricePerNight: 1200,
    amenities: ["Hill Views", "Restaurant", "Trekking Guides", "Parking", "Basic Facilities", "Nature Walks"],
    roomTypes: ["Standard Room", "Dormitory", "Family Suite"],
    nearbyAttractions: ["Environmental Park", "Viewpoints", "Nature Trails"],
    features: ["Hill Station Experience", "Budget-Friendly", "Government Run", "Nature Setting"]
  },
  {
    id: 13,
    name: "Traveler's Inn",
    location: "Kadapa",
    category: "Budget",
    type: "Transit Hotel",
    description: "Simple accommodation for travelers exploring historical sites",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/t/t3/Travelers_inn.jpg/800px-Travelers_inn.jpg",
    rating: 3.6,
    pricePerNight: 1400,
    amenities: ["Restaurant", "WiFi", "Travel Information", "Luggage Storage", "Local Tours", "Parking"],
    roomTypes: ["Standard Room", "Twin Sharing", "Family Room"],
    nearbyAttractions: ["Gandikota", "Belum Caves", "Sidhout Fort"],
    features: ["Historical Tours", "Budget Travel", "Local Guides", "Clean Accommodation"]
  },
  {
    id: 14,
    name: "Beach Stay Hotel",
    location: "Nellore",
    category: "Budget",
    type: "Beach Hotel",
    description: "Basic beachside accommodation with easy access to coast",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Beach_budget_hotel.jpg/800px-Beach_budget_hotel.jpg",
    rating: 3.4,
    pricePerNight: 1600,
    amenities: ["Beach Access", "Seafood Restaurant", "WiFi", "Beach Equipment Rental", "Parking", "Room Service"],
    roomTypes: ["Sea View Room", "Standard Room", "Family Room"],
    nearbyAttractions: ["Mypadu Beach", "Pulicat Lake", "Nelapattu Bird Sanctuary"],
    features: ["Beach Access", "Seafood Dining", "Bird Watching", "Coast Exploration"]
  },
  {
    id: 15,
    name: "Pilgrims Rest",
    location: "Srisailam",
    category: "Budget",
    type: "Pilgrim Lodge",
    description: "Simple accommodation for devotees visiting the sacred Jyotirlinga",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/p/p7/Pilgrim_lodge.jpg/800px-Pilgrim_lodge.jpg",
    rating: 3.8,
    pricePerNight: 1000,
    amenities: ["Temple Shuttle", "Vegetarian Meals", "Prayer Facilities", "Early Check-in", "Luggage Storage", "Spiritual Programs"],
    roomTypes: ["Basic Room", "Shared Accommodation", "Family Room"],
    nearbyAttractions: ["Srisailam Temple", "Krishna River", "Mallikarjuna Wildlife Sanctuary"],
    features: ["Spiritual Atmosphere", "Temple Services", "Devotee Facilities", "Affordable Pilgrimage"]
  }
];